$ErrorActionPreference = "Stop"
& .\VERIFY_V243R29_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R29 baseline verification failed" }
python -c "from hip_id_agent.edit_section_learning import build_fields, input_json_from_fields, EditSectionMemory, ALL_PHASES; from hip_id_agent.portal_skills import canonical_operation; from hip_id_agent.config import AppConfig; f = build_fields([{'id': 'a', 'type': 'radio', 'label': 'Yes', 'group_label': 'Existing Account *', 'group_name': 'ea', 'checked': True}, {'id': 'b', 'type': 'radio', 'label': 'No', 'group_label': 'Existing Account *', 'group_name': 'ea'}, {'id': 'c', 'type': 'password', 'label': 'SFTP Password', 'value': 'x'}]); assert [(x['label'], x['value']) for x in f] == [('Existing Account', 'Yes'), ('SFTP Password', '********')]; f[0]['input_key'] = 'existing_account'; assert input_json_from_fields('source_transport_profile', f)['objects']['source_transport_profile'] == {'existing_account': 'Yes'}; assert canonical_operation('learn edit') == 'learn_edit' and canonical_operation('edit') == 'edit'; assert len(ALL_PHASES) == 7 and AppConfig().edit_sections.block_read_only_changes; print('R30_EDIT_SECTION_CAPTURE_OK')"
if ($LASTEXITCODE -ne 0) { throw "R30 edit section capture smoke failed" }
python -c "import inspect; from hip_id_agent import portal_operations as p, task_operations as t; from hip_id_agent.browser_session import BrowserSession; from hip_id_agent.config import AppConfig; src = inspect.getsource(p.PortalOperationRunner.run_one); assert '_capture_edit_section' in src and '_read_only_changes' in src and 'read_back_edit_form' in src; assert 'learned_then_replayed' in inspect.getsource(p.PortalOperationRunner.fill); specs = t.task_operation_specs('open the Transport profile, click the expand button and the Edit button and capture all the values, same for the Bizflow and all the phases'); assert [s['operation'] for s in specs] == ['learn_edit'] * 7 and specs[0]['phase'] == 'source_transport_profile'; s = BrowserSession(AppConfig(), __import__('pathlib').Path('.hip_runtime/verify_r30')); assert not s._is_sso_transition_url('https://developer.dell.com/hybrid-integrations/securelink/bizflows/edit/U-HAUL_PC_856_ANS_MAPPING_OB') and s._is_sso_transition_url('https://myaccess.dell.com/x'); print('R30_EDIT_OPERATIONS_USE_EDIT_SECTION_OK')"
if ($LASTEXITCODE -ne 0) { throw "R30 edit operations smoke failed" }
Write-Host "V243R30 install verification PASS" -ForegroundColor Green
Write-Host "Every phase's Edit section is learned (listing > expand > Edit > every value), remembered, and used by Edit operations."
