$ErrorActionPreference = "Stop"
& .\VERIFY_V243R38_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R38 baseline verification failed" }
python -c "import inspect; import hip_id_agent.bizflow_kb as k; assert hasattr(k, '_click_bizflow_wizard_button') and hasattr(k, 'learn_bizflow_tab_options') and hasattr(k, '_record_bizflow_navigation'); src = inspect.getsource(k._ensure_bizflow_tab_open); assert 'wizard_next' in src and 'HIP_BIZFLOW_NEXT_BLOCKED' in src; assert 'notRowAdder' in inspect.getsource(k._click_bizflow_section_add); assert 'inPage' in inspect.getsource(k._click_bizflow_template_link_after_add); assert 'legacy_fill' in inspect.getsource(k.capture_and_fill_bizflow_multitab_form); print('R39_BIZFLOW_WIZARD_OK')"
if ($LASTEXITCODE -ne 0) { throw "R39 BizFlow wizard smoke failed" }
python -c "import tempfile, pathlib; from hip_id_agent.phase_navigation import record, load; from hip_id_agent.deterministic_script import build_script; d = pathlib.Path(tempfile.mkdtemp()); record(d, 'biz_flow', {'entry': ['+ Add', 'template link B2B-Flow-PubSub-Template'], 'wizard': True, 'tabs': [{'tab': 'Flow Details', 'advance': 'Next'}, {'tab': 'Configure Routing'}]}); s = build_script(phase='biz_flow', skill_data={}, navigation=load(d, 'biz_flow')); t = [x['text'] for x in s['steps']]; assert any('template link' in x for x in t) and any(x.startswith('Click') and 'Next' in x for x in t); from hip_id_agent.operation_learning import OPERATIONS, operation_matrix; m = operation_matrix(d, ['biz_flow']); assert m['operations'] == list(OPERATIONS) and m['total'] == 5; from hip_id_agent.config import AppConfig; c = AppConfig(); assert c.operation_learning.enabled and c.operation_learning.actions == ['edit', 'clone', 'migrate', 'deploy']; print('R39_NAVIGATION_AND_OPERATION_MATRIX_OK')"
if ($LASTEXITCODE -ne 0) { throw "R39 navigation / operation matrix smoke failed" }
python -c "import pathlib; names = ('index.html', 'app.js', 'styles.css'); assert all(pathlib.Path('webui', n).read_bytes() == pathlib.Path('backend', 'webui', n).read_bytes() for n in names); html = pathlib.Path('webui', 'index.html').read_text(encoding='utf-8'); js = pathlib.Path('webui', 'app.js').read_text(encoding='utf-8'); assert 'operationMatrixPanel' in html and 'function loadOperationMatrix' in js and '/api/operation-matrix' in js; api = pathlib.Path('backend', 'app.py').read_text(encoding='utf-8'); assert '/api/operation-matrix' in api; print('R39_CONTROL_CENTER_OPERATIONS_OK')"
if ($LASTEXITCODE -ne 0) { throw "R39 Control Center smoke failed" }
Write-Host "V243R39 install verification PASS" -ForegroundColor Green
Write-Host "BizFlow: + Add > template link > wizard tabs with Next; every phase learns Create / Edit / Clone / Migrate / Deploy."
