$ErrorActionPreference = "Stop"
& .\VERIFY_V243R30_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R30 baseline verification failed" }
python -c "import tempfile, pathlib; from hip_id_agent.edit_section_learning import SectionMemory, action_summaries; from hip_id_agent.portal_operations import PortalOperationRunner as R; d = pathlib.Path(tempfile.mkdtemp()); m = SectionMemory(d, 'migrate'); m.record('rule', {'section_kind': 'menu', 'menus': {'DEV': ['TEST1', 'TEST2'], 'TEST2': ['PROD']}}); assert m.route('rule', 'DEV', 'PROD') == ['DEV', 'TEST2', 'PROD']; assert R._not_offered({'target_environment': 'PROD'}, [{'label': 'Target Environment', 'options': ['TEST1', 'TEST2']}])[0]['offered'] == ['TEST1', 'TEST2']; assert R._confirm_template('Deploy X_1 version 1.0 from DEV to TEST1?', 'X_1') == 'Deploy <object> version <version> from DEV to TEST1?'; assert action_summaries(d)['migrate']['known'] == 1; print('R31_ACTION_SECTIONS_OK')"
if ($LASTEXITCODE -ne 0) { throw "R31 action sections smoke failed" }
python -c "import inspect; from hip_id_agent import portal_operations as p, task_operations as t, edit_section_learning as e; src = inspect.getsource(p.PortalOperationRunner.run_one); assert '_confirm_choice' in src and 'learn_clone' in src and '_capture_action_dialog' in src; assert '_settle_guarded_opener' in inspect.getsource(p.PortalOperationRunner.open_surface); assert '_learned_targets' in inspect.getsource(p.PortalOperationRunner._open_panel_action); assert '_learn_promotion' in inspect.getsource(e.EditSectionLearner.learn); (c,) = t.task_operation_specs('clone transport profile SFTP_A_IB as SFTP_A_IB_V2 and save'); assert c['values'] == {'profile_name': 'SFTP_A_IB_V2'} and c['target'] == 'SFTP_A_IB'; assert [s['operation'] for s in t.task_operation_specs('learn the deploy and migrate sections of the bizflow')] == ['learn_deploy', 'learn_migrate']; print('R31_CLONE_DEPLOY_MIGRATE_EVERY_PHASE_OK')"
if ($LASTEXITCODE -ne 0) { throw "R31 clone/deploy/migrate smoke failed" }
Write-Host "V243R31 install verification PASS" -ForegroundColor Green
Write-Host "Clone / Deploy / Migrate work on every phase (menu, dialog or confirmation), are learned read-only and remembered."
