$ErrorActionPreference = "Stop"
& .\VERIFY_V243R35_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R35 baseline verification failed" }
python -c "from hip_id_agent.section_judge import DualModelSectionJudge as J, SectionJudgePolicy as P; j = J(P(enabled=True, require_text_model=False, require_vision_model=False, max_repairs=0, fail_closed=True)); e = {'facts': [{'field': 'status', 'input_path': 'status', 'value': 'Enabled', 'aliases': ['Status']}]}; c = {'label': 'Status', 'role': 'switch', 'type': 'button', 'value': '', 'checked': True}; r = j.deterministic_judge(expected=e, actual_state={'controls': [c], 'visible_text': ''}); assert r['pass'] and r['matched_values'][0]['evidence'] == 'checked_state'; c['checked'] = False; assert not j.deterministic_judge(expected=e, actual_state={'controls': [c], 'visible_text': ''})['pass']; from hip_id_agent.input_json_authority import _BUSY_JS; assert '[role=navigation]' in _BUSY_JS; print('R36_SWITCH_AND_BUSY_OK')"
if ($LASTEXITCODE -ne 0) { throw "R36 switch / busy smoke failed" }
python -c "import tempfile, pathlib, time; from hip_id_agent import operator_control as o, operator_chat as q; d = pathlib.Path(tempfile.mkdtemp()); o.bind(d); o.confirm_complete(d, 'source_document_type', text='everything filled correctly'); o._S.last_read = 0.0; assert o.confirmed_complete('source_document_type'); p = o.confirmed_proof('source_document_type', {'pass': False, 'missing_fields': ['status'], 'matched_fields': ['a'], 'actual_control_count': 9, 'invalid_fields': []}); assert p['pass'] and p['operator_confirmed_fields'] == ['status']; assert not o.confirmed_proof('source_document_type', {'pass': False, 'missing_fields': ['status'], 'actual_control_count': 9, 'invalid_fields': ['Version']})['pass']; o.unbind(); assert [q.interpret(x) for x in ('everything filled correctly', 'status is wrong', 'status?', 'is everything filled correctly?')] == ['accept', 'hint', 'status', 'hint']; assert q.interpret('status is wrong', review_pending=True) == 'reject'; print('R36_OPERATOR_CONFIRMATION_OK')"
if ($LASTEXITCODE -ne 0) { throw "R36 operator confirmation smoke failed" }
python -c "import inspect; from hip_id_agent import dummy_fill_e2e as m, browser_session as b, model_qualification as q; from hip_id_agent.config import AppConfig; s = inspect.getsource(m); assert '_ask_before_reopening(' in s and '_kept_form_preflight(' in s; assert '_release_or_replace_cdp_port' in inspect.getsource(b.BrowserSession.restart); assert q.QUALIFICATION_VERSION == 3; c = AppConfig(); assert c.runtime_self_heal.ask_before_reopening_max_missing == 2 and c.model_portfolio.qualification_retries == 1 and c.agent_chat.model_intent_fallback; j = open('webui/app.js', encoding='utf-8').read(); assert 'question:' in j and 'st.review.question' in j and open('webui/app.js', 'rb').read() == open('backend/webui/app.js', 'rb').read(); print('R36_MISSION_WIRING_OK')"
if ($LASTEXITCODE -ne 0) { throw "R36 mission wiring smoke failed" }
Write-Host "V243R36 install verification PASS" -ForegroundColor Green
Write-Host "A filled form finishes; 'everything is filled correctly' in the chat confirms a phase; a nearly complete form is asked about, not reopened."
