$ErrorActionPreference = "Stop"
& .\VERIFY_V243R13_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R13 baseline verification failed" }
python -c "from hip_id_agent.stateful_form_runtime import compile_phase_state_graph as c; from hip_id_agent.autonomous_dependency_runtime import apply_dependency_execution_contract as a; from hip_id_agent.form_interaction_policy import eligible_child_nodes as e; o={'name':'N','data_format_type':'XML','document_identifier':{'operation':'All conditions are satisfied','rows':[{'derived_from':'TRANSACTION_ROOT_ELEMENT','value':'V'}]},'attributes_to_configure':[{'attribute_name':'Receiver','derived_from':'ELEMENT_IN_PAYLOAD','usage':'Logging','expression':'/x'}],'validation_type':'Structure'}; g=a(c({'objects':{'source_document_type':o}},'source_document_type'),phase='source_document_type'); n={x['field_key']:x for x in g['nodes']}; ks={x['field_key'] for x in e(g,n['data_format_type']['node_id'],{n['document_type_name']['node_id']:True})}; assert not ks & {'document_identifier_value','attribute_expression'}, ks; assert e(g,n['document_type_name']['node_id'],{})==[]; print('R14_CHILD_GATE_ONLY_REVEALED_CHILDREN_OK')"
if ($LASTEXITCODE -ne 0) { throw "R14 child-gate smoke failed" }
python -c "from hip_id_agent.stateful_form_runtime import compile_phase_state_graph as c; from hip_id_agent.autonomous_dependency_runtime import apply_dependency_execution_contract as a; from hip_id_agent.form_interaction_policy import structural_dependencies as s; o={'name':'N','data_format_type':'XML','attributes_to_configure':[{'attribute_name':'Receiver','derived_from':'ELEMENT_IN_PAYLOAD','usage':'Logging'}],'validation_type':'Structure'}; g=a(c({'objects':{'source_document_type':o}},'source_document_type'),phase='source_document_type'); n={x['field_key']:x for x in g['nodes']}; assert s(g,n['validation_type'])==[n['data_format_type']['node_id']]; print('R14_ORDERING_EDGES_DO_NOT_CASCADE_OK')"
if ($LASTEXITCODE -ne 0) { throw "R14 dependency-cascade smoke failed" }
python -c "from hip_id_agent.form_interaction_policy import scroll_control_into_view, scroll_locator_into_view; from hip_id_agent.stateful_form_runtime import scroll_control_into_view as wired; print('R14_SCROLL_INTO_VIEW_WIRED_OK')"
if ($LASTEXITCODE -ne 0) { throw "R14 scroll wiring smoke failed" }
Write-Host "V243R14 install verification PASS" -ForegroundColor Green
Write-Host "Document Type fills every section (identifier, attributes, validation) and repairs failed fields on the next adaptive cycle."
