$ErrorActionPreference = "Stop"
& .\VERIFY_V243R31_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R31 baseline verification failed" }
python -c "from hip_id_agent.config import AppConfig; from hip_id_agent.portal_form_exploration import explore_after_fill, form_changed_by_exploration; from hip_id_agent.runtime_self_heal import RuntimeSelfHealController as H; from hip_id_agent.environment_faults import ENVIRONMENT_FATAL_CODES, whitelabel_message; c = AppConfig(); assert explore_after_fill(c) is False and c.autonomous_form.stop_when_input_json_exact is True; assert c.runtime_self_heal.refill_probe_seconds == 120 and c.runtime_self_heal.whitelabel_browser_restarts == 3; assert not form_changed_by_exploration({'completeness': {'parent_values_live_explored': 0}}); m = whitelabel_message({'status': '500'}, 'rule form'); assert 'HIP_WHITELABEL_ERROR_PAGE' in ENVIRONMENT_FATAL_CODES and H.classify_failure(m) == 'whitelabel_error_page' and H.CLASS_ACTIONS['whitelabel_error_page'] == ('restart_browser_session',); print('R32_STOP_AND_WHITELABEL_OK')"
if ($LASTEXITCODE -ne 0) { throw "R32 stop/whitelabel smoke failed" }
python -c "import inspect; from hip_id_agent import autonomous_form_runtime as a, phase_progress as p, dummy_fill_e2e as d, phase_live_reproof as r; assert '_input_json_exact_result' in inspect.getsource(a.execute_autonomous_phase_goal) and 'newly_proven' in inspect.getsource(a.execute_autonomous_phase_goal); w = inspect.getsource(p.run_with_progress_watchdog); assert 'refill_loop' in w and 'whitelabel_error' in w; s = inspect.getsource(d); assert 'pre_judge_gate' in s and '_quiet_completion_probe' in s; g = r._radio_group_answers([{'type': 'radio', 'group_label': 'Use Existing Folder', 'label': 'No', 'checked': True}]); assert g[0]['value'] == 'No'; print('R32_ENGINE_WATCHDOG_PROOF_OK')"
if ($LASTEXITCODE -ne 0) { throw "R32 engine/watchdog smoke failed" }
Write-Host "V243R32 install verification PASS" -ForegroundColor Green
Write-Host "A complete form is no longer filled again; a Whitelabel Error Page closes and reopens the browser and restarts the stage."
