$ErrorActionPreference = "Stop"
& .\VERIFY_V243R28_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R28 baseline verification failed" }
python -c "import inspect; from hip_id_agent import input_json_authority as a, section_judge as j, dummy_fill_e2e as m; from hip_id_agent.config import AppConfig; assert j._values_equal('ELEMENT_IN_PAYLOAD', 'Element In Payload') and not j._values_equal('ELEMENT_IN_PAYLOAD', 'Transaction Root Element'); g, d, o = a.accept_exact_phase({'pass': False}, {'reasons': [1]}, {'pass': True}); assert o and g['pass'] and not d; g, d, o = a.accept_exact_phase({'pass': False}, {'reasons': [1]}, {'pass': False}); assert not o and d; src = inspect.getsource(m.FullDummyFillE2EFlow.run); assert 'accept_exact_phase(judge_result, diagnosis, input_authority)' in src and 'attempt_{attempt_no}_error' in src; h = AppConfig().human_in_the_loop; assert h.input_json_exact_is_authoritative and not h.review_learning_phase_even_when_exact; print('R29_INPUT_JSON_EXACT_COMPLETES_PHASE_OK')"
if ($LASTEXITCODE -ne 0) { throw "R29 input.json authority smoke failed" }
python -c "import inspect; from hip_id_agent import model_qualification as q, live_runtime_certification as l; from hip_id_agent.config import AppConfig; assert q.QUALIFICATION_VERSION == 2 and q.revalidation_reason({'locked': True}) == 'qualification_version_upgrade'; s = {'headers': ['Name', 'Format', 'Type'], 'rows': [{'name': 'A', 'cells': ['A', 'XML', '850']}, {'name': 'B', 'cells': ['B', 'EDI', '856']}], 'controls': []}; qs = q.build_judge_questions(s); assert [x['expected']['match'] for x in qs] == [True, False]; assert 'revalidation_reason(existing, cfg)' in inspect.getsource(l.qualify_models_on_live_page); m = AppConfig().model_portfolio; assert m.qualification_min_judge_accuracy == 0.5 and m.qualification_revalidate_after_judge_errors == 3; print('R29_ALL_MODELS_REVALIDATED_CHAMPION_OK')"
if ($LASTEXITCODE -ne 0) { throw "R29 champion revalidation smoke failed" }
Write-Host "V243R29 install verification PASS" -ForegroundColor Green
Write-Host "An exactly filled form completes its phase; every model is re-validated (navigation + completion judgments) and the champion chosen."
