$ErrorActionPreference = "Stop"
& .\VERIFY_V243R34_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R34 baseline verification failed" }
python -c "import json, tempfile, pathlib; from hip_id_agent import agent_chat as c; d = pathlib.Path(tempfile.mkdtemp()); f = c.activate(c.AgentChatFeed(d)); P = type('P', (), {})(); c.executor_step(P, phase='rule', node={'node_id': 'n', 'field_key': 'interface_type', 'expected_value': 'SFTP HAFT'}, stage='start'); c.broker_action(P, action='click', label='HIP Portal DDS option SFTP HAFT', success=True); c.say('x', kind='info'); c.deactivate(f); r = c.read_chat(d); t = [m['text'] for m in r['messages']]; assert t == ['Selected \u201cSFTP HAFT\u201d in Interface Type', 'x'], t; assert c.read_chat(d, cursor=r['cursor'])['messages'] == []; assert c.display_value('password', 'p') == c.MASK; print('R35_CHAT_FEED_OK')"
if ($LASTEXITCODE -ne 0) { throw "R35 chat feed smoke failed" }
python -c "import tempfile, pathlib, time; from hip_id_agent import operator_control as o, operator_chat as q; d = pathlib.Path(tempfile.mkdtemp()); o.bind(d); o.write_control(d, 'paused'); time.sleep(0.3); assert o.is_paused(); o.write_control(d, 'running'); time.sleep(0.25); assert not o.is_paused() and o.paused_seconds() >= 0.29; o.unbind(); assert [q.interpret(x) for x in ('status', 'pause', 'resume', 'stop', 'what is left?', 'accept', 'it is on the Connection tab')] == ['status', 'pause', 'resume', 'stop', 'left', 'accept', 'hint']; print('R35_OPERATOR_CONTROL_OK')"
if ($LASTEXITCODE -ne 0) { throw "R35 operator control smoke failed" }
python -c "import inspect, backend.app as b; from hip_id_agent import phase_progress as p, dummy_fill_e2e as m; from hip_id_agent.config import AppConfig; assert all(hasattr(b, n) for n in ('mission_chat', 'mission_chat_post', 'mission_chat_frame')); assert 'operator_control.work_clock()' in inspect.getsource(p) and 'agent_chat.live_frame_loop(' in inspect.getsource(m); assert AppConfig().agent_chat.enabled is True; h = open('webui/index.html', encoding='utf-8').read(); assert 'chatDock' in h and 'chatOpenBtn' in h and open('webui/index.html', 'rb').read() == open('backend/webui/index.html', 'rb').read(); print('R35_BACKEND_CHAT_OK')"
if ($LASTEXITCODE -ne 0) { throw "R35 backend chat smoke failed" }
Write-Host "V243R35 install verification PASS" -ForegroundColor Green
Write-Host "The live agent chat narrates every action; status, pause / resume / stop and hints work from the chat."
