$ErrorActionPreference = "Stop"
& .\VERIFY_V243R27_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R27 baseline verification failed" }
python -c "import inspect; from hip_id_agent import dds_control_driver as d, stateful_form_runtime as f; from hip_id_agent.environment_faults import ENVIRONMENT_FATAL_CODES as E; assert d.snapshot_options_empty({'found': True, 'options': [], 'no_data': True}) and not d.snapshot_options_empty({'found': True, 'options': [], 'list_loading': True}); assert 'EMPTY_OPTIONS_CODE' in inspect.getsource(d.select_dds_combobox) and 'EMPTY_OPTIONS_CODE' in inspect.getsource(d.select_dds_multiselect); assert '_raise_if_dropdown_options_empty(' in inspect.getsource(f.execute_document_type_state_graph) and '_raise_if_dropdown_options_empty(' in inspect.getsource(f.execute_phase_state_graph); assert 'HIP_DROPDOWN_OPTIONS_EMPTY' in E; print('R28_EMPTY_DROPDOWN_DETECTED_OK')"
if ($LASTEXITCODE -ne 0) { throw "R28 empty dropdown detection smoke failed" }
python -c "import inspect; from hip_id_agent.runtime_self_heal import RuntimeSelfHealController as R; from hip_id_agent.config import AppConfig; from hip_id_agent import dummy_fill_e2e as m; assert R.classify_failure('HIP_DROPDOWN_OPTIONS_EMPTY: the Usage dropdown opened with no values; value mismatch') == 'dropdown_options_empty'; assert R.CLASS_ACTIONS['dropdown_options_empty'] == ('restart_browser_session',) and R.LADDER_FAMILIES['dropdown_options_empty'] == 'lists'; assert AppConfig().runtime_self_heal.empty_options_browser_restarts == 2; assert 'HIP_DROPDOWN_OPTIONS_EMPTY_AFTER_RECOVERY' in inspect.getsource(m.FullDummyFillE2EFlow.run); print('R28_RESTART_BROWSER_RECOVERY_OK')"
if ($LASTEXITCODE -ne 0) { throw "R28 recovery smoke failed" }
Write-Host "V243R28 install verification PASS" -ForegroundColor Green
Write-Host "A dropdown that keeps listing no values closes and reopens the browser, returns to the same page, opens the form and fills it again (at most twice per phase)."
