$ErrorActionPreference = "Stop"
& .\VERIFY_V243R14_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R14 baseline verification failed" }
python -c "from hip_id_agent.stateful_form_runtime import compile_phase_state_graph as c; from hip_id_agent.autonomous_dependency_runtime import apply_dependency_execution_contract as a; from hip_id_agent.form_interaction_policy import structural_dependencies as s; o={'system_type':'Dell Application','partner_name':'AIC - DCE','profile_name':'P','profile_usage':'Sender','deployment_group':'G','interface_type':'SFTP HAFT'}; g=a(c({'objects':{'source_transport_profile':o}},'source_transport_profile'),phase='source_transport_profile'); n={x['field_key']:x for x in g['nodes']}; assert s(g,n['profile_name'])==[] and s(g,n['partner_name'])==[n['system_type']['node_id']]; print('R15_TP_CHAIN_ONLY_REAL_PARENTS_OK')"
if ($LASTEXITCODE -ne 0) { throw "R15 transport-profile chain smoke failed" }
python -c "from hip_id_agent.stateful_form_runtime import _stateful_control_score as sc, _protected_state_changes as ch, _effective_action as ea; n={'field_key':'existing_account','action':'select_radio','expected_value':'Yes','section':'Create Transport Profile','semantic_locator':{'labels':['Existing Account']}}; r=lambda g:{'type':'radio','label':'Yes','group_label':g,'section':'Primary Interface Detail :','interactable':True}; assert sc(r('Existing Account *'),n)-sc(r('Use Existing Folder *'),n)>=14; assert ch({'x':{'value':'A','selected_values':[],'identity':'0'}},{'x':{'value':'A','selected_values':['a'],'identity':'k'}})==[]; assert ea({'action':'fill_text'},{'role':'combobox'})=='select_single'; print('R15_RADIO_GROUPS_MUTATION_AND_LIVE_ACTION_OK')"
if ($LASTEXITCODE -ne 0) { throw "R15 radio/mutation/action smoke failed" }
python -c "from hip_id_agent.autonomous_form_runtime import _display_only_evidence as d; assert d({'field_key':'current_flow_version','value':'1','input_path':'x'},'Current Flow version : 1.0'); assert not d({'field_key':'description','value':'x','input_path':'x'},'Description x'); print('R15_PORTAL_DISPLAY_VALUES_OK')"
if ($LASTEXITCODE -ne 0) { throw "R15 display-value smoke failed" }
python -c "from hip_id_agent.universal_portal_operator import resolve_hip_phase_for_task as r; p={'objects':{'rule':{'name':'R'},'source_transport_profile':{'profile_name':'S'},'target_transport_profile':{'profile_name':'T'}}}; assert r(task='create a new rule from input json',input_root='',payload=p)=='rule'; assert r(task='create the target transport profile',input_root='',payload=p)=='target_transport_profile'; assert r(task='fill the transport profile form',input_root='',payload=p)==''; print('R15_TASK_BOX_PHASE_ROUTING_OK')"
if ($LASTEXITCODE -ne 0) { throw "R15 task-box routing smoke failed" }
Write-Host "V243R15 install verification PASS" -ForegroundColor Green
Write-Host "Every phase fills its whole form (Data Map, Document Types, Rule, Transport Profiles, BizFlow tabs); the task box uses the learned phase knowledge."
