$ErrorActionPreference = "Stop"
& .\VERIFY_V243R26_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R26 baseline verification failed" }
python -c "import inspect; from hip_id_agent.browser_session import BrowserSession as B; from hip_id_agent.config import AppConfig; from hip_id_agent import live_runtime_certification as l; c = AppConfig(); assert c.portal.navigation_render_wait_seconds == 90 and c.portal.navigation_render_wait_max_seconds == 300; s = inspect.getsource(B._react_ensure_target_surface); assert 'await_route_render' in s and 'reload_target' in s; b = B(c, __import__('pathlib').Path(__import__('tempfile').mkdtemp())); b._learned_render_wait_seconds = {'doctypes': 150.0}; assert b._navigation_render_budget('https://developer.dell.com/hybrid-integrations/securelink/doctypes') == 150.0; assert 'kept_previous_selection' in inspect.getsource(l.qualify_models_on_live_page); print('R27_ROUTE_RENDER_WAIT_AND_MODEL_KEPT_OK')"
if ($LASTEXITCODE -ne 0) { throw "R27 route render wait smoke failed" }
python -c "import inspect, json, tempfile, pathlib; from hip_id_agent.config import AppConfig; from hip_id_agent import dummy_fill_e2e as d; from hip_id_agent.run_history_learning import run_history_learner_from_config; t = pathlib.Path(tempfile.mkdtemp()); c = AppConfig(); c.reporting.runs_dir = str(t / 'runs'); c.reporting.memory_dir = str(t / 'memory'); r = t / 'runs' / 'R1'; r.mkdir(parents=True); (r / 'mission_state.json').write_text(json.dumps({'mission_status': 'complete', 'phases': {'source_document_type': {'status': 'complete', 'attempts': 1, 'started_at': '2026-09-28T10:00:00+00:00', 'completed_at': '2026-09-28T10:30:00+00:00'}}})); (r / 'mlflow_async_events.jsonl').write_text(json.dumps({'event': 'phase_completed', 'payload': {'phase': 'source_document_type', 'judge_pass': True, 'duration_seconds': 1800.0}}) + chr(10)); x = run_history_learner_from_config(c).learn(include_mlflow=False); assert x['runs_learned'] == 1 and x['lessons']['min_attempt_seconds']['source_document_type'] == 2250; src = inspect.getsource(d.FullDummyFillE2EFlow.run); assert 'run_history_learner_from_config(self.config).learn' in src and 'apply_lessons(' in src; print('R27_RUN_HISTORY_LEARNING_OK')"
if ($LASTEXITCODE -ne 0) { throw "R27 run-history learning smoke failed" }
python -c "import importlib.util, tempfile, pathlib; from hip_id_agent.config import AppConfig; from hip_id_agent.mlflow_async import AsyncMLflowTracker; ok = importlib.util.find_spec('mlflow') is not None; t = pathlib.Path(tempfile.mkdtemp()); s = AsyncMLflowTracker(AppConfig().mlflow, run_id='VERIFY', run_dir=t / 'runs' / 'VERIFY', phases=['x']).start() if ok else {}; assert (not ok) or s.get('available'), s.get('last_error'); print('R27_MLFLOW_LOCAL_STORE_OK' if ok else 'R27_MLFLOW_NOT_INSTALLED_RUN_FOLDERS_ONLY')"
if ($LASTEXITCODE -ne 0) { throw "R27 MLflow local store smoke failed" }
Write-Host "V243R27 install verification PASS" -ForegroundColor Green
Write-Host "A slowly rendering listing is waited for (then reloaded once), a failed model re-run keeps the earlier model, MLflow records runs again, and every mission learns from the past runs first."
