$ErrorActionPreference = "Stop"
& .\VERIFY_V243R37_INSTALL.ps1
if ($LASTEXITCODE -ne 0) { throw "R37 baseline verification failed" }
python -c "from hip_id_agent.runtime_self_heal import RuntimeSelfHealController as R; assert R.classify_failure('HIP_ROUTE_STUCK_LOADING: stuck') == 'portal_loading_stuck'; from hip_id_agent.browser_session import BrowserSession as B; assert B.ROUTE_RECOVERY_STEPS == ('wait', 'reload', 'portal_menu', 'fresh_document'); assert hasattr(B, '_route_recovery_ladder') and hasattr(B, '_module_still_loading'); from hip_id_agent.config import AppConfig; c = AppConfig(); assert c.runtime_self_heal.route_recovery_enabled and c.runtime_self_heal.handoff_restart_browser_on_stuck_route; assert c.human_in_the_loop.incomplete_phase_wait_seconds_when_more_phases == 900 and c.human_in_the_loop.deferred_phase_retries == 1; print('R38_ROUTE_RECOVERY_AND_DEFERRAL_OK')"
if ($LASTEXITCODE -ne 0) { throw "R38 route recovery smoke failed" }
python -c "import json, tempfile, pathlib; from hip_id_agent.deterministic_script import build_script, render_markdown; skill = {'skills': {'s': {'skill_id': 's', 'operation': 'create', 'status': 'candidate', 'bindings': {'map_identifier': {'action': 'fill_text'}}, 'stats': {}}}}; s = build_script(phase='data_map', skill_data=skill, url='https://developer.dell.com/hybrid-integrations/securelink/datamaps'); md = render_markdown(s); assert s['status'] == 'candidate' and s['values_stored'] is False and 'input.json' in md and 'Click' in md; from hip_id_agent.doctype_kb import _defer_row_deficit_to_goal_engine; w = []; a = {'summary': {'exact_row_count_pass': False}}; _defer_row_deficit_to_goal_engine(a, w, stage='t'); assert a['deferred_to_goal_engine']; print('R38_DETERMINISTIC_SCRIPT_OK')"
if ($LASTEXITCODE -ne 0) { throw "R38 deterministic script smoke failed" }
python -c "import pathlib; names = ('index.html', 'app.js', 'styles.css'); assert all(pathlib.Path('webui', n).read_bytes() == pathlib.Path('backend', 'webui', n).read_bytes() for n in names); html = pathlib.Path('webui', 'index.html').read_text(encoding='utf-8'); js = pathlib.Path('webui', 'app.js').read_text(encoding='utf-8'); assert 'deterministicScriptsPanel' in html and 'function loadDeterministicScripts' in js and '/api/deterministic-scripts' in js; api = pathlib.Path('backend', 'app.py').read_text(encoding='utf-8'); assert '/api/deterministic-scripts' in api; print('R38_CONTROL_CENTER_SCRIPTS_OK')"
if ($LASTEXITCODE -ne 0) { throw "R38 Control Center smoke failed" }
Write-Host "V243R38 install verification PASS" -ForegroundColor Green
Write-Host "Missions recover pages that never load, continue past a phase that needs you, and show each phase's deterministic script."
